server:
  port: 8806
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://bj-cdb-0srt3yo9.sql.tencentcdb.com:63422/pra?characterEncoding=utf-8
    username: root
    password: Qlxlm123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server
    client:
      ipAddress: 192.168.0.222
  redis:
  #################redis基础配置#################
    database: 8
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.0.222:8888/eureka/
  instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true

# mybatis
mybatis:
  mapper-locations:  classpath:mapping/*/*.xml
  type-aliases-package: com.prostate.*.entity
#httpClient 配置信息
http:
  maxTotal: 80
  defaultMaxPerRoute: 80
  connectTimeout: 30000
  connectionRequestTimeout: 30000
  socketTimeout: 30000
  staleConnectionCheckEnabled: true