spring:
  datasource:
    url: jdbc:mysql://bj-cdb-0srt3yo9.sql.tencentcdb.com:63422/pra?characterEncoding=utf-8
    username: root
    password: Qlxlm123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
  #################redis基础配置#################
    database: 8
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
