spring:
  profiles:
    active: dev
#  datasource:
#    jdbc-url: jdbc:mysql://bj-cdb-0srt3yo9.sql.tencentcdb.com:63422/pra?characterEncoding=utf-8
#    username: root
#    password: Qlxlm123456
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.221:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    slaver:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.221:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server
  redis:
  #################redis基础配置#################
    database: 8
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8888/eureka/

feign:
  hystrix:
    enabled: true

# mybatis
mybatis:
  mapper-locations:  classpath:mapping/**/*.xml
  type-aliases-package: com.prostate.*.entity
