spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://bj-cdb-0srt3yo9.sql.tencentcdb.com:63422/pra?characterEncoding=utf-8
    username: root
    password: Qlxlm123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server
  redis:
  #################redis基础配置#################
    database: 8
#    host: 192.168.0.63
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8888/eureka/

zuul:
  routes:
    api-a:
      path: /api-user/**
      service-id: user-server
    api-aa:
      path: /api-doctor/**
      service-id: user-server
    api-b:
      path: /api-third/**
      service-id: third-server
    api-bb:
      path: /api-file/**
      service-id: third-server
    api-c:
      path: /api-stata/**
      service-id: stata-server
    api-d:
      path: /api-record/**
      service-id: record-server
    api-e:
      path: /api-assessmen/**
      service-id: assessmen-server
    api-f:
      path: /api-order/**
      service-id: order-server
    api-g:
      path: /api-wallet/**
      service-id: wallet-server
ribbon:
  ReadTimeout: 40000
  ConnectTimeout: 40000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 40000



